# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-J5_L6NmXZQNxtWRtccfD36cB46QvuW8
"""

a = 2
b = 4
print(a + b +a)

a = 2
b = 4
c = 2
print(a == b)
print(a == c)

a = 10
b = 12
print(a + b)

minha_lista = [10, 20, 30, 40, 50]
print(minha_lista[2])

letras = ["a", "b", "c", "d"]
print("O segundo elemento é: ", letras[1])

letras = ["a", "b", "c", "d", "e", "f"]
print("Os elementos são: ", letras[3:7])

letras = ["a", "b", "c", "d", "e", "f"]
print("Os elementos são: ", letras[:7])

letras = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
print("Os elementos são: ", letras[-1])

letras = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
print("Os elementos são: ", letras[-4:])

letras = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
print("Os elementos são: ", letras[::2])





lista1 = [1, 2, 3, 4, 5]
print("O Terceiro elemento: ", lista1[2])

lista2 = [10, 20, 30, 40, 50]
print("A Soma dos elementos é:", sum(lista2))

frutas = ["maça", "banana", "laranja" ]
print("Primeiro elemento: ", frutas[0])
print("O último elemento é: ", frutas[2])

lista3 = []
lista3.append(10)
lista3.append(20)
lista3.append(30)
print("Lista após adição: ", lista3)

lista4 = [1, 2, 2, 3, 4, 4, 4, 5]
print("O total de vezes que o numero 4 aparece é: ", lista4.count(4))

lista5 = [1, 2, 2, 3, 4, 4, 5]
lista_sem_duplicatas = list(set(lista5))
print("A lista sem duplicatas é: ", lista_sem_duplicatas)

lista6 = [3, 32, 14, 22, 17]
print("Lista original: ", lista6)
print("Ordenada Crescente: ", sorted(lista6))
print("Ordenada Decrescente: ", sorted(lista6, reverse=True))

lista7 = [10, 20, 30, 40, 50]
media = sum(lista7) / len(lista7)
print("A Média dos elementos é: ", media)

lista8 = [1, 2, 3, 4, 5]
lista_invertida = []
for i in range(len(lista8)-1, -1, -1):
  lista_invertida.append(lista8[i])
print("Lista invertida: ", lista_invertida)

lista9 = [1, 2, 3, 4]
lista10 = [3, 4, 5, 6]
intersecao = [x for x in lista9 if x in lista10]
print("A intersecao é: ", intersecao)