# -*- coding: utf-8 -*-
"""Atividade2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_hmeGz4ot3gkSSpNfsQyqrFVhPDXAsVV
"""

import numpy as np

vetor1 = np.array([11, 22, 33, 44])
vetor2 = np.array([56, 67, 78, 89])

soma = vetor1 + vetor2
print("Soma dos valores:", soma)

import numpy as np

vetor1 = np.array([1, 3, -5])
vetor2 = np.array([4, -2, -1])

produto_escalar = np.dot(vetor1, vetor2)
print("Produto escalar: ", produto_escalar)

import numpy as np

vetor = np.array([3, 4])

magnitude = np.linalg.norm(vetor)
vetor_normalizado = vetor / magnitude
print("Vetor Normalizado: ", vetor_normalizado)

import numpy as np

vetor = np.array([3, 4])

magnitude = np.linalg.norm(vetor)
print("Magnitude do vetor: ", magnitude)

import numpy as np

vetor = np.array([10, 20, 30, 40, 50])

soma_elementos = np.sum(vetor)
print("Soma dos elementos do vetor: ", soma_elementos)

#1 Exercicio
origem = "facebook"
brinde = False
if origem == "google":
  brinde = True
print(brinde)

#2 Exercicio
my_range = range(1, 11)
print(list(my_range))

#2 Exericicio + teste
my_range = range(-5, 1000)
print(list(my_range))

#3 Exercicio
lista_de_numeros = range(1, 20)
lista_de_numeros = [str(numero) for numero in lista_de_numeros]
print(lista_de_numeros)

#4 Exercicio
lista_de_numeros = range(1, 21)
lista_de_numeros = [numero * 10 for numero in lista_de_numeros]
print(lista_de_numeros)

#5 Exercicio
a = [1, 2, 2, 3, 1, "1", 2, 3]
a = set(a)
print(a)

#6 Exercicio
dict_pessoa = {"Nome": "Felipe", "Idade": 26}
print(dict_pessoa)

#7 Exercicio
#6 Exercicio
dict_pessoa = {"Nome": "Felipe", "Idade": 26}
print(dict_pessoa['Idade'])

#8 Exercicio
d = {"a": 10, "b": 10}
print(d['a'] +  d['b'])

#9 Exercicio
d = {"Nome": "Diego", "Sobrenome": "Silva", "Idade": 29}
print(d["Sobrenome"])

#10 Exercicio
d = {"a": 1, "b": 2, "c": 3, "d": 4, "e": 5, "f": 6}
print(sum(d.values()))