# -*- coding: utf-8 -*-
"""Atividade 8 -  Estrutura de dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EADFr6UQEhI-OpBaGMS7zXcBI3tABM-7
"""

#Exercicio 1

import numpy as np

# Matriz A(3x2)
A = np.array(([1, 2], [3, 4], [5,6]))

# Transporta de A

A_transposta = np.transpose(A)

print("Transposta de A:", A_transposta)

#Exercicio 2

import numpy as np

# Vetor V
v = np.array([3, 4, 5])

# Norma do vetor V
norm_v = np.linalg.norm(v)

print("Norma do vetor:", norm_v)

#Exercicio 3

import numpy as np

# Vetor V
v = np.array([2, 3, 4])

# Escalar k
k = 5

# Multiplicação escalar
v_scaled = k * v

print("Vetor escalado:", v_scaled)

#Exercicio 4

import numpy as np
import scipy.linalg

# Matriz A
A = np.array([[4, 3, 2], [2, 1, 3], [3, 2, 4]])

# Decomposição LU de A
P, L ,U = scipy.linalg.lu(A)

print("Matriz P (permutação):", P)
print("Matriz L (lower triangular):", L)
print("Matriz U (upper triangular):", U)

#Exercicio 5

import numpy as np

# Vetores u e v
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Produto interno
dot_product = np.dot(u, v)

print("Produto interno:", dot_product)