# -*- coding: utf-8 -*-
"""EstruturaDeDados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yR4A2nUm8ixDWJzLOFxL3Y1KyD2ZVE8Z
"""

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

C = A + B
print("Matriz C (A + B):\n", C)

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

D = A * B
print("Matriz D (A * B elemento a elemento):\n", D)

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

E = np.dot(A, B)
print("Matriz E (A * B produto matricial):\n", E)

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

soma_C = np.sum(C)
print("Soma de todos os elementos de C:", soma_C)

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

D_transposta = D.T
print("Transposta da matriz D:\n", D_transposta)

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

max_E = np.max(E)
min_E = np.min(E)
print("Valor máximo de E:", max_E)
print("Valor minimo de E:", min_E)