# -*- coding: utf-8 -*-
"""Fila em Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wG1nRhvI9Yeyet9N91Yskes6gKAP_OdC
"""

from collections import deque

# Fila Vazia
fila = deque()

# Botando na fila os elementos
fila.append('A')
fila.append('B')
fila.append('C')

print("Fila após enfileirar elementos:", list(fila))

# Tirando os elementos da fila
primeiro = fila.popleft()
print("Elemento removido:", primeiro)
print("Fila após retirar elemento:", list(fila))

# Verificando o primeiro elemento (sem remover)
frente = fila[0]
print("Primeiro elemento da fila:", frente)

# Verificando se a fila está vazia
vazia = len(fila) == 0
print("Fila está vazia?", vazia)

"""***Exercicios***"""

#Exercicio 1
from collections import deque

fila = deque()

fila.append('Elemento 1')
fila.append('Elemento 2')
fila.append('Elemento 3')
fila.append('Elemento 4')
fila.append('Elemento 5')

print("Fila após add 5 elementos:", list(fila))

#Exercicio 1
primeiro_elemento = fila.popleft()

print("Elemento removido:", primeiro_elemento)
print("Fila após remover o primeiro elemento:", list(fila))

#Exercicio 2
fila = deque([1, 2, 3, 4])

while fila:
  print("Removendo:", fila.popleft())

print("Fila está vazia?", len(fila) == 0)

#Exercicio 3
fila = deque([10, 20, 30])
print("Primeiro elemento sem remover:", fila[0])

#Exercicio 4
def lista_para_fila(lista):
  fila = deque(lista)
  return fila

fila = lista_para_fila([1, 2, 3, 4])
print("Fila criada:", list(fila))

#Exercicio 5

def inverter_fila(fila):
  fila.reverse()
  return fila

fila = deque([1, 2, 3, 4, 5])
fila_invertida = inverter_fila(fila)
print("Fila invertida:", list(fila_invertida))

#Exercicio 6
fila = deque(['Cliente 1', 'Cliente 2', 'Cliente 3', 'Cliente 4', 'Cliente 5'])

while fila:
  cliente_atendido = fila.popleft()
  print(f"Atendendo {cliente_atendido}")

#Exercicio 7
fila = deque([10, 20, 30, 40, 50])

soma = sum(fila)
print("Soma dos elementos da fila:", soma)